main :  startswith.o look_for_local_ip.o
	cc -o look_fd startswith.o look_for_local_ip.o
look_for_local_ip.o : look_for_local_ip.c
	cc -c look_for_local_ip.c
startswith.o : startswith.c
	cc -c startswith.c


